config/routes.rb
Ccs::Application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  resources :users
  match 'speakers' => 'users#index'

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  match '/admin' => 'admin_home#index'

  resources :posts

  get "notifications/speaker_notification"
  get "notification/speaker_notification"

  resources :schedules
  match '/schedule' => "schedules#index"

  resources :rooms

  resources :time_slots

  resources :sponsors

  resources :sponsorship_levels

  resources :features

  resources :sesjas, :path => "sessions" do
    resources :comments
  end

  resources :contents
  resources :imports
  resources :preregistrations, :only => [:create, :index]

  match '/submissions/accept/:id', controller: "submissions", action: "accept"
  match '/submissions/reject/:id', controller: "submissions", action: "reject"
  resources :submissions


  match '/import/proc/:id' => 'imports#proc_csv', :as => :import_proc

  match '/:path' => 'contents#show' # this needs to be the last non-default route

  root :to => 'sesjas#index'
  #root :to => 'submissions#new'
  #root :to => "contents#show"

end
#== Route Map
# Generated on 10 Feb 2012 09:40
#
#                       user_session POST       /d/users/sign_in(.:format)                      {:action=>"create", :controller=>"devise/sessions"}
#               destroy_user_session DELETE     /d/users/sign_out(.:format)                     {:action=>"destroy", :controller=>"devise/sessions"}
#                      user_password POST       /d/users/password(.:format)                     {:action=>"create", :controller=>"devise/passwords"}
#                  new_user_password GET        /d/users/password/new(.:format)                 {:action=>"new", :controller=>"devise/passwords"}
#                 edit_user_password GET        /d/users/password/edit(.:format)                {:action=>"edit", :controller=>"devise/passwords"}
#                                    PUT        /d/users/password(.:format)                     {:action=>"update", :controller=>"devise/passwords"}
#           cancel_user_registration GET        /d/users/cancel(.:format)                       {:action=>"cancel", :controller=>"devise/registrations"}
#                  user_registration POST       /d/users(.:format)                              {:action=>"create", :controller=>"devise/registrations"}
#              new_user_registration GET        /d/users/sign_up(.:format)                      {:action=>"new", :controller=>"devise/registrations"}
#             edit_user_registration GET        /d/users/edit(.:format)                         {:action=>"edit", :controller=>"devise/registrations"}
#                                    PUT        /d/users(.:format)                              {:action=>"update", :controller=>"devise/registrations"}
#                                    DELETE     /d/users(.:format)                              {:action=>"destroy", :controller=>"devise/registrations"}
#                  user_confirmation POST       /d/users/confirmation(.:format)                 {:action=>"create", :controller=>"devise/confirmations"}
#              new_user_confirmation GET        /d/users/confirmation/new(.:format)             {:action=>"new", :controller=>"devise/confirmations"}
#                                    GET        /d/users/confirmation(.:format)                 {:action=>"show", :controller=>"devise/confirmations"}
#             accept_user_invitation GET        /d/users/invitation/accept(.:format)            {:action=>"edit", :controller=>"devise/invitations"}
#                    user_invitation POST       /d/users/invitation(.:format)                   {:action=>"create", :controller=>"devise/invitations"}
#                new_user_invitation GET        /d/users/invitation/new(.:format)               {:action=>"new", :controller=>"devise/invitations"}
#                                    PUT        /d/users/invitation(.:format)                   {:action=>"update", :controller=>"devise/invitations"}
#                              users GET        /users(.:format)                                {:action=>"index", :controller=>"users"}
#                                    POST       /users(.:format)                                {:action=>"create", :controller=>"users"}
#                           new_user GET        /users/new(.:format)                            {:action=>"new", :controller=>"users"}
#                          edit_user GET        /users/:id/edit(.:format)                       {:action=>"edit", :controller=>"users"}
#                               user GET        /users/:id(.:format)                            {:action=>"show", :controller=>"users"}
#                                    PUT        /users/:id(.:format)                            {:action=>"update", :controller=>"users"}
#                                    DELETE     /users/:id(.:format)                            {:action=>"destroy", :controller=>"users"}
#                           speakers            /speakers(.:format)                             {:action=>"index", :controller=>"users"}
#                    admin_dashboard            /admin(.:format)                                {:action=>"index", :controller=>"admin/dashboard"}
#                     admin_contents GET        /admin/contents(.:format)                       {:action=>"index", :controller=>"admin/contents"}
#                                    POST       /admin/contents(.:format)                       {:action=>"create", :controller=>"admin/contents"}
#                  new_admin_content GET        /admin/contents/new(.:format)                   {:action=>"new", :controller=>"admin/contents"}
#                 edit_admin_content GET        /admin/contents/:id/edit(.:format)              {:action=>"edit", :controller=>"admin/contents"}
#                      admin_content GET        /admin/contents/:id(.:format)                   {:action=>"show", :controller=>"admin/contents"}
#                                    PUT        /admin/contents/:id(.:format)                   {:action=>"update", :controller=>"admin/contents"}
#                                    DELETE     /admin/contents/:id(.:format)                   {:action=>"destroy", :controller=>"admin/contents"}
#                     admin_features GET        /admin/features(.:format)                       {:action=>"index", :controller=>"admin/features"}
#                                    POST       /admin/features(.:format)                       {:action=>"create", :controller=>"admin/features"}
#                  new_admin_feature GET        /admin/features/new(.:format)                   {:action=>"new", :controller=>"admin/features"}
#                 edit_admin_feature GET        /admin/features/:id/edit(.:format)              {:action=>"edit", :controller=>"admin/features"}
#                      admin_feature GET        /admin/features/:id(.:format)                   {:action=>"show", :controller=>"admin/features"}
#                                    PUT        /admin/features/:id(.:format)                   {:action=>"update", :controller=>"admin/features"}
#                                    DELETE     /admin/features/:id(.:format)                   {:action=>"destroy", :controller=>"admin/features"}
#                        admin_posts GET        /admin/posts(.:format)                          {:action=>"index", :controller=>"admin/posts"}
#                                    POST       /admin/posts(.:format)                          {:action=>"create", :controller=>"admin/posts"}
#                     new_admin_post GET        /admin/posts/new(.:format)                      {:action=>"new", :controller=>"admin/posts"}
#                    edit_admin_post GET        /admin/posts/:id/edit(.:format)                 {:action=>"edit", :controller=>"admin/posts"}
#                         admin_post GET        /admin/posts/:id(.:format)                      {:action=>"show", :controller=>"admin/posts"}
#                                    PUT        /admin/posts/:id(.:format)                      {:action=>"update", :controller=>"admin/posts"}
#                                    DELETE     /admin/posts/:id(.:format)                      {:action=>"destroy", :controller=>"admin/posts"}
#                        admin_rooms GET        /admin/rooms(.:format)                          {:action=>"index", :controller=>"admin/rooms"}
#                                    POST       /admin/rooms(.:format)                          {:action=>"create", :controller=>"admin/rooms"}
#                     new_admin_room GET        /admin/rooms/new(.:format)                      {:action=>"new", :controller=>"admin/rooms"}
#                    edit_admin_room GET        /admin/rooms/:id/edit(.:format)                 {:action=>"edit", :controller=>"admin/rooms"}
#                         admin_room GET        /admin/rooms/:id(.:format)                      {:action=>"show", :controller=>"admin/rooms"}
#                                    PUT        /admin/rooms/:id(.:format)                      {:action=>"update", :controller=>"admin/rooms"}
#                                    DELETE     /admin/rooms/:id(.:format)                      {:action=>"destroy", :controller=>"admin/rooms"}
#                    admin_schedules GET        /admin/schedules(.:format)                      {:action=>"index", :controller=>"admin/schedules"}
#                                    POST       /admin/schedules(.:format)                      {:action=>"create", :controller=>"admin/schedules"}
#                 new_admin_schedule GET        /admin/schedules/new(.:format)                  {:action=>"new", :controller=>"admin/schedules"}
#                edit_admin_schedule GET        /admin/schedules/:id/edit(.:format)             {:action=>"edit", :controller=>"admin/schedules"}

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :sesja
  belongs_to :room
  belongs_to :time_slot

  default_scope includes(:time_slot).where('schedules.version_tag = ?', VERSION_TAG).order('time_slots.starts_at ASC')

  scope :with_sessions, includes(:sesja).where('schedules.sesja_id is not null')
  scope :with_rooms, includes(:room).where('schedules.room_id is not null')
  scope :with_time_slots, includes(:time_slot).where('schedules.time_slot_id is not null')

  class << self
    def assigned
      Schedule.with_rooms.with_time_slots
    end

    def last_updated_at
      sql = <<-SQL
select max(updated_at) as last_updated_at
from (
  select max(updated_at) as updated_at from schedules
  union
  select max(updated_at) as updated_at from time_slots
  union
  select max(updated_at) as updated_at from sesjas
  union
  select max(updated_at) as updated_at from rooms
) as updates;
      SQL
      DateTime.parse(ActiveRecord::Base.connection.execute(sql).first["last_updated_at"])

    end
  end
end

# == Schema Information
#
# Table name: schedules
#
#  id           :integer         not null, primary key
#  sesja_id     :integer
#  room_id      :integer
#  time_slot_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#  version_tag  :string(255)
#

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  load_and_authorize_resource
  caches_page [:index, :show]

  def index
    response.headers['Cache-Control'] = "public, max-age=#{CACHE_CONTROL__MAX_AGE}"
    @schedules = Schedule.assigned.group_by {|s| s.time_slot.title }
    @last_updated_at = Schedule.last_updated_at

    respond_to do |format|
      if params.keys.include? "printable"
        format.html { render :layout => false,
          :template => "schedules/printable" }
      else
        format.html
      end
      format.atom { render :layout => false }
    end
  end

  def show
    response.headers['Cache-Control'] = "public, max-age=#{CACHE_CONTROL__MAX_AGE}"

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  def new
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  def edit
  end

  def create
    @schedule.version_tag = VERSION_TAG
    respond_to do |wants|
      if @schedule.save

        expire_page :action => :index
        wants.html { redirect_to(@schedule, :notice => 'Schedule was successfully created.') }
      else
        wants.html { render :action => "new" }
      end
      wants.atom { render :action => "index", :layout => false }
    end
  end

  def update
    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        expire_page :action => :index
        format.html { redirect_to(@schedule, :notice => 'Schedule was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @schedule.destroy
    expire_page :action => :index

    respond_to do |format|
      format.html { redirect_to(schedules_url) }
    end
  end
end

app/views/schedules/_form.html.haml
= semantic_form_for @schedule do |f|
  = f.inputs do
    = f.input :sesja, :as => :select, :collection => Sesja.displayable,
      :include_blank => true, :member_label => :title
    = f.input :room, :as => :select, :collection => Room.all,
      :include_blank => true, :member_label => :title
    = f.input :time_slot, :as => :select, :collection => TimeSlot.all,
      :include_blank => true, :member_label => :title
  = f.buttons

-# <%= form_for(@schedule) do |f| %>
-#   <% if @schedule.errors.any? %>
-#     <div id="error_explanation">
-#       <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

-#       <ul>
-#       <% @schedule.errors.full_messages.each do |msg| %>
-#         <li><%= msg %></li>
-#       <% end %>
-#       </ul>
-#     </div>
-#   <% end %>

-#   <div class="field">
-#     <%= f.label :sesja %><br />
-#     <%= f.text_field :sesja %>
-#   </div>
-#   <div class="field">
-#     <%= f.label :room %><br />
-#     <%= f.text_field :room %>
-#   </div>
-#   <div class="field">
-#     <%= f.label :time_slot %><br />
-#     <%= f.text_field :time_slot %>
-#   </div>
-#   <div class="actions">
-#     <%= f.submit %>
-#   </div>
-# <% end %>

app/views/schedules/_schedule.html.haml
%h3.sponsorship-level= raw "<span>#{schedule.time_slot.title}:</span> #{schedule.time_slot.start_and_end_time}"
= render :partial => "show", :collection => schedule

app/views/schedules/_show.html.haml
.show
  %ul
    %li.schedule.session
      /
        = show.id
      %a{:href => "#"}= show.room.title
      %span // 
      - if show.sesja.present?
        = link_to show.sesja.title, sesja_path(show.sesja)
        %span with 
        = link_to show.sesja.user.full_name, user_path(show.sesja.user)
      - else
        = show.time_slot.title
    - if user_signed_in? && current_user.admin?
      .actions
        %ul
          %li= link_to 'Show', show 
          %li= link_to 'Edit', edit_schedule_path(show)
          %li= link_to 'Destroy', show, :confirm => 'Are you sure you wish to delete this schedule?', :method => :delete

app/views/schedules/edit.html.erb
<h1>Editing schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.haml
= auto_discovery_link_tag(:atom)

%h4.section-title schedule
- if user_signed_in? && current_user.admin?
  = render :partial => "shared/actions", :locals => {:model => Schedule.new, :current_action => :index}

.print-bar
  = link_to "print-friendly schedule", schedules_path(Schedule.new,:printable => true)

.lineup
  - @schedules.each_pair do |key, value|
    %h3.sponsorship-level= raw "<span>#{key}:</span> #{value.first.time_slot.start_and_end_time}"
    = render :partial => "show", :collection => value

app/views/schedules/new.html.erb
<h1>New schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/printable.html.haml
- rooms = @schedules.values.map {|k| k.map {|v| v.room.title if v.sesja}}.flatten!.compact!.uniq!.sort!
- time_slots = @schedules.map {|k| k.first }
!!!
%html
  %head
    %title Chicago Code Camp 2012 - May 19th
    %meta{:content => "Chicago Code Camp is a free, one day conference on Saturday May 19th for developers of all skill levels and interests with multiple sessions running side-by-side throughout the day.", :name => "description"}/
    %meta{:charset => "utf-8"}
    = stylesheet_link_tag "printable", :media => "all"
    = csrf_meta_tag
  %body
    .logo
      - if Feature.ok? :image_logo
        = link_to image_tag("logo-horizontal.png", :border => 0), root_url
      - else
        = link_to "chicago code camp", root_url
    %table
      %thead
        %tr
          %th
          - time_slots.each do |time_slot|
            %th= time_slot
      %tbody
        - counter = 1
        - rooms.each do |r|
          - cls = counter % 2 == 0 ? 'even' : 'odd'
          %tr{:class => "#{cls}"}
            - counter = counter + 1
            %td.left-column= r
            - @schedules.each_pair do |key, value|
              - v = value.select {|s| s.room.title == r}.first
              - if v.nil?
                %td{:class => "#{cls}"}= raw("&nbsp;")
              - elsif v.sesja
                %td{:class => "#{cls}"}
                  .title= v.sesja.title
                  .speaker= "by #{v.sesja.user.full_name}"
              - else
                %td{:class => "#{cls} yellie"}= raw("&nbsp;")

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sesja:</b>
  <%= @schedule.sesja %>
</p>

<p>
  <b>Room:</b>
  <%= @schedule.room %>
</p>

<p>
  <b>Time slot:</b>
  <%= @schedule.time_slot %>
</p>


<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>