config/routes.rb
Ccs::Application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  resources :users
  match 'speakers' => 'users#index'

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  match '/admin' => 'admin_home#index'

  resources :posts

  get "notifications/speaker_notification"
  get "notification/speaker_notification"

  resources :schedules
  match '/schedule' => "schedules#index"

  resources :rooms

  resources :time_slots

  resources :sponsors

  resources :sponsorship_levels

  resources :features

  resources :sesjas, :path => "sessions" do
    resources :comments
  end

  resources :contents
  resources :imports
  resources :preregistrations, :only => [:create, :index]

  match '/submissions/accept/:id', controller: "submissions", action: "accept"
  match '/submissions/reject/:id', controller: "submissions", action: "reject"
  resources :submissions


  match '/import/proc/:id' => 'imports#proc_csv', :as => :import_proc

  match '/:path' => 'contents#show' # this needs to be the last non-default route

  root :to => 'sesjas#index'
  #root :to => 'submissions#new'
  #root :to => "contents#show"

end
#== Route Map
# Generated on 10 Feb 2012 09:40
#
#                       user_session POST       /d/users/sign_in(.:format)                      {:action=>"create", :controller=>"devise/sessions"}
#               destroy_user_session DELETE     /d/users/sign_out(.:format)                     {:action=>"destroy", :controller=>"devise/sessions"}
#                      user_password POST       /d/users/password(.:format)                     {:action=>"create", :controller=>"devise/passwords"}
#                  new_user_password GET        /d/users/password/new(.:format)                 {:action=>"new", :controller=>"devise/passwords"}
#                 edit_user_password GET        /d/users/password/edit(.:format)                {:action=>"edit", :controller=>"devise/passwords"}
#                                    PUT        /d/users/password(.:format)                     {:action=>"update", :controller=>"devise/passwords"}
#           cancel_user_registration GET        /d/users/cancel(.:format)                       {:action=>"cancel", :controller=>"devise/registrations"}
#                  user_registration POST       /d/users(.:format)                              {:action=>"create", :controller=>"devise/registrations"}
#              new_user_registration GET        /d/users/sign_up(.:format)                      {:action=>"new", :controller=>"devise/registrations"}
#             edit_user_registration GET        /d/users/edit(.:format)                         {:action=>"edit", :controller=>"devise/registrations"}
#                                    PUT        /d/users(.:format)                              {:action=>"update", :controller=>"devise/registrations"}
#                                    DELETE     /d/users(.:format)                              {:action=>"destroy", :controller=>"devise/registrations"}
#                  user_confirmation POST       /d/users/confirmation(.:format)                 {:action=>"create", :controller=>"devise/confirmations"}
#              new_user_confirmation GET        /d/users/confirmation/new(.:format)             {:action=>"new", :controller=>"devise/confirmations"}
#                                    GET        /d/users/confirmation(.:format)                 {:action=>"show", :controller=>"devise/confirmations"}
#             accept_user_invitation GET        /d/users/invitation/accept(.:format)            {:action=>"edit", :controller=>"devise/invitations"}
#                    user_invitation POST       /d/users/invitation(.:format)                   {:action=>"create", :controller=>"devise/invitations"}
#                new_user_invitation GET        /d/users/invitation/new(.:format)               {:action=>"new", :controller=>"devise/invitations"}
#                                    PUT        /d/users/invitation(.:format)                   {:action=>"update", :controller=>"devise/invitations"}
#                              users GET        /users(.:format)                                {:action=>"index", :controller=>"users"}
#                                    POST       /users(.:format)                                {:action=>"create", :controller=>"users"}
#                           new_user GET        /users/new(.:format)                            {:action=>"new", :controller=>"users"}
#                          edit_user GET        /users/:id/edit(.:format)                       {:action=>"edit", :controller=>"users"}
#                               user GET        /users/:id(.:format)                            {:action=>"show", :controller=>"users"}
#                                    PUT        /users/:id(.:format)                            {:action=>"update", :controller=>"users"}
#                                    DELETE     /users/:id(.:format)                            {:action=>"destroy", :controller=>"users"}
#                           speakers            /speakers(.:format)                             {:action=>"index", :controller=>"users"}
#                    admin_dashboard            /admin(.:format)                                {:action=>"index", :controller=>"admin/dashboard"}
#                     admin_contents GET        /admin/contents(.:format)                       {:action=>"index", :controller=>"admin/contents"}
#                                    POST       /admin/contents(.:format)                       {:action=>"create", :controller=>"admin/contents"}
#                  new_admin_content GET        /admin/contents/new(.:format)                   {:action=>"new", :controller=>"admin/contents"}
#                 edit_admin_content GET        /admin/contents/:id/edit(.:format)              {:action=>"edit", :controller=>"admin/contents"}
#                      admin_content GET        /admin/contents/:id(.:format)                   {:action=>"show", :controller=>"admin/contents"}
#                                    PUT        /admin/contents/:id(.:format)                   {:action=>"update", :controller=>"admin/contents"}
#                                    DELETE     /admin/contents/:id(.:format)                   {:action=>"destroy", :controller=>"admin/contents"}
#                     admin_features GET        /admin/features(.:format)                       {:action=>"index", :controller=>"admin/features"}
#                                    POST       /admin/features(.:format)                       {:action=>"create", :controller=>"admin/features"}
#                  new_admin_feature GET        /admin/features/new(.:format)                   {:action=>"new", :controller=>"admin/features"}
#                 edit_admin_feature GET        /admin/features/:id/edit(.:format)              {:action=>"edit", :controller=>"admin/features"}
#                      admin_feature GET        /admin/features/:id(.:format)                   {:action=>"show", :controller=>"admin/features"}
#                                    PUT        /admin/features/:id(.:format)                   {:action=>"update", :controller=>"admin/features"}
#                                    DELETE     /admin/features/:id(.:format)                   {:action=>"destroy", :controller=>"admin/features"}
#                        admin_posts GET        /admin/posts(.:format)                          {:action=>"index", :controller=>"admin/posts"}
#                                    POST       /admin/posts(.:format)                          {:action=>"create", :controller=>"admin/posts"}
#                     new_admin_post GET        /admin/posts/new(.:format)                      {:action=>"new", :controller=>"admin/posts"}
#                    edit_admin_post GET        /admin/posts/:id/edit(.:format)                 {:action=>"edit", :controller=>"admin/posts"}
#                         admin_post GET        /admin/posts/:id(.:format)                      {:action=>"show", :controller=>"admin/posts"}
#                                    PUT        /admin/posts/:id(.:format)                      {:action=>"update", :controller=>"admin/posts"}
#                                    DELETE     /admin/posts/:id(.:format)                      {:action=>"destroy", :controller=>"admin/posts"}
#                        admin_rooms GET        /admin/rooms(.:format)                          {:action=>"index", :controller=>"admin/rooms"}
#                                    POST       /admin/rooms(.:format)                          {:action=>"create", :controller=>"admin/rooms"}
#                     new_admin_room GET        /admin/rooms/new(.:format)                      {:action=>"new", :controller=>"admin/rooms"}
#                    edit_admin_room GET        /admin/rooms/:id/edit(.:format)                 {:action=>"edit", :controller=>"admin/rooms"}
#                         admin_room GET        /admin/rooms/:id(.:format)                      {:action=>"show", :controller=>"admin/rooms"}
#                                    PUT        /admin/rooms/:id(.:format)                      {:action=>"update", :controller=>"admin/rooms"}
#                                    DELETE     /admin/rooms/:id(.:format)                      {:action=>"destroy", :controller=>"admin/rooms"}
#                    admin_schedules GET        /admin/schedules(.:format)                      {:action=>"index", :controller=>"admin/schedules"}
#                                    POST       /admin/schedules(.:format)                      {:action=>"create", :controller=>"admin/schedules"}
#                 new_admin_schedule GET        /admin/schedules/new(.:format)                  {:action=>"new", :controller=>"admin/schedules"}
#                edit_admin_schedule GET        /admin/schedules/:id/edit(.:format)             {:action=>"edit", :controller=>"admin/schedules"}

app/views/shared/_actions.html.haml
- model_name = display_name(model.class.to_s) if model
%fieldset.actions
  %legend= "Manage #{model_name}"
  %ul
    - if can?(:index, model)
      %li= link_to "Manage your #{model_name.pluralize}", polymorphic_path(model.class)

    - unless [:new].include? current_action
      - if can?(:create, model)
        %li= link_to "Create another #{model_name}", polymorphic_path(model.class, :action => "new")

    - unless [:new, :create, :index].include? current_action
      - if can?(:show, model)
        %li= link_to "View #{model_name}", polymorphic_path(model)

      - if can?(:update, model)
        %li= link_to "Edit this #{model_name}", polymorphic_path(model, :action => "edit")

      - if can?(:destroy, model)
        %li= link_to "Destroy this #{model_name}", model, :confirm => "Are you sure you wish to delete this #{model_name}?", :method => :delete

app/views/shared/_authentication.html.haml
.aside.authentication
  - if user_signed_in?
    = form_tag destroy_user_session_path do
      %h5 logged in as...
      %p= link_to current_user.email, user_path(current_user)
      %fieldset
        = button "logout", destroy_user_session_path
  - else
    = semantic_form_for(User.new(:email => @email), :as => 'user', :url => session_path('user')) do |f|
      %h5 speaker login
      %p.login-to Login to manage your sessions.
      - f.inputs do
        = f.input :email, :placeholder => "your.login@email.com", required: true
        = f.input :password, required: true
      - f.buttons do
        = f.commit_button label: "login"
        %li= link_to "Forgot your password?", new_password_path('user')

app/views/shared/_blurb.html.haml
.aside.blurb
  %h5 What is CCC?
  %p Chicago Code Camp is a free, one day conference on Saturday May 19th, for developers of all skill levels and interests with multiple sessions running side-by-side throughout the day.

app/views/shared/_color_proof.html.haml
#color-proof
  .greyish
    this is a greyish block
  .c-left
    this is a c-left block
  .c-left-33
    this is a c-left-33 block
  .c-left-66
    this is a c-left-66 block
  .primary
    this is a primary block
  .primary-33
    this is a primary-33 block
  .primary-66
    this is a primary-66 block
  .c-right
    this is a c-right block
  .c-right-33
    this is a c-right-33 block
  .c-right-66
    this is a c-right-66 block
  .neutral
    this is the neutral block
  .tbd
    this is a tbd block

app/views/shared/_getsatisfaction.html.haml
%script{:charset => "utf-8", :type => "text/javascript", :language=>"javascript"}
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));

%script{:charset => "utf-8", :type => "text/javascript", :language => "javascript"}
  var feedback_widget_options = {};

  feedback_widget_options.display = "overlay";
  feedback_widget_options.company = "#{ENV['APP']}";
  feedback_widget_options.placement = "left";
  feedback_widget_options.color = "#800000";
  feedback_widget_options.style = "idea";

  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);

app/views/shared/_github.html.haml
%a{:href => "#{ENV['GITHUB_URL']}"}
  %img{:style => "position: absolute; top: 0; right: 0; border: 0; z-index: -1;", :src => "http://s3.amazonaws.com/github/ribbons/forkme_right_white_ffffff.png", :alt => "Fork me on GitHub"}

app/views/shared/_google_analytics.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '#{ENV['GA_ACCOUNT']}']);
  _gaq.push(['_setDomainName', '.#{ENV['GA_DOMAIN_NAME']}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script');
    ga.type = 'text/javascript';
    ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_google_font_loader.html.haml
%script{:src => "https://www.google.com/jsapi", :type => "text/javascript"}
:javascript
  google.load("webfont", "1");
  google.setOnLoadCallback(function() {
    WebFont.load({google: {families:['Syncopate','Ubuntu:regular,italic,bold,bolditalic','Slackey']}});
  });

app/views/shared/_location.html.haml
.aside.location
  %h5 Where is CCC?
  %p
    College of Lake County
    19351 W. Washington Str.
    Grayslake, IL 60030-1198

app/views/shared/_preregistrations.html.haml
- unless user_signed_in?
  .aside.preregistration
    %h5 Register for Updates
    %p
      Stay up-to-date on the latest announcements and news related to CCC3.
    = form_for Preregistration.new, :method => :post do |f|
      %fieldset
        %ol
          %li
            = f.label :email, "email"
            = f.email_field :email, :placeholder => "your.login@email.com"
      %fieldset
        %ol
          %li
            %button#preregistration_submit{:name => "commit", :type => "submit"} register for updates

app/views/shared/_register.html.haml
.aside.register
  %h5 Registration is open!
  %p
    %a{href: 'http://chicagocodecamp2012.eventbrite.com?ref=ecount'} Click to register for Chicago Code Camp 2012 on EventBrite.