config/routes.rb
Ccs::Application.routes.draw do

  devise_for :users, :path_prefix => 'd'
  resources :users
  match 'speakers' => 'users#index'

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  match '/admin' => 'admin_home#index'

  resources :posts

  get "notifications/speaker_notification"
  get "notification/speaker_notification"

  resources :schedules
  match '/schedule' => "schedules#index"

  resources :rooms

  resources :time_slots

  resources :sponsors

  resources :sponsorship_levels

  resources :features

  resources :sesjas, :path => "sessions" do
    resources :comments
  end

  resources :contents
  resources :imports
  resources :preregistrations, :only => [:create, :index]

  match '/submissions/accept/:id', controller: "submissions", action: "accept"
  match '/submissions/reject/:id', controller: "submissions", action: "reject"
  resources :submissions


  match '/import/proc/:id' => 'imports#proc_csv', :as => :import_proc

  match '/:path' => 'contents#show' # this needs to be the last non-default route

  root :to => 'sesjas#index'
  #root :to => 'submissions#new'
  #root :to => "contents#show"

end
#== Route Map
# Generated on 10 Feb 2012 09:40
#
#                       user_session POST       /d/users/sign_in(.:format)                      {:action=>"create", :controller=>"devise/sessions"}
#               destroy_user_session DELETE     /d/users/sign_out(.:format)                     {:action=>"destroy", :controller=>"devise/sessions"}
#                      user_password POST       /d/users/password(.:format)                     {:action=>"create", :controller=>"devise/passwords"}
#                  new_user_password GET        /d/users/password/new(.:format)                 {:action=>"new", :controller=>"devise/passwords"}
#                 edit_user_password GET        /d/users/password/edit(.:format)                {:action=>"edit", :controller=>"devise/passwords"}
#                                    PUT        /d/users/password(.:format)                     {:action=>"update", :controller=>"devise/passwords"}
#           cancel_user_registration GET        /d/users/cancel(.:format)                       {:action=>"cancel", :controller=>"devise/registrations"}
#                  user_registration POST       /d/users(.:format)                              {:action=>"create", :controller=>"devise/registrations"}
#              new_user_registration GET        /d/users/sign_up(.:format)                      {:action=>"new", :controller=>"devise/registrations"}
#             edit_user_registration GET        /d/users/edit(.:format)                         {:action=>"edit", :controller=>"devise/registrations"}
#                                    PUT        /d/users(.:format)                              {:action=>"update", :controller=>"devise/registrations"}
#                                    DELETE     /d/users(.:format)                              {:action=>"destroy", :controller=>"devise/registrations"}
#                  user_confirmation POST       /d/users/confirmation(.:format)                 {:action=>"create", :controller=>"devise/confirmations"}
#              new_user_confirmation GET        /d/users/confirmation/new(.:format)             {:action=>"new", :controller=>"devise/confirmations"}
#                                    GET        /d/users/confirmation(.:format)                 {:action=>"show", :controller=>"devise/confirmations"}
#             accept_user_invitation GET        /d/users/invitation/accept(.:format)            {:action=>"edit", :controller=>"devise/invitations"}
#                    user_invitation POST       /d/users/invitation(.:format)                   {:action=>"create", :controller=>"devise/invitations"}
#                new_user_invitation GET        /d/users/invitation/new(.:format)               {:action=>"new", :controller=>"devise/invitations"}
#                                    PUT        /d/users/invitation(.:format)                   {:action=>"update", :controller=>"devise/invitations"}
#                              users GET        /users(.:format)                                {:action=>"index", :controller=>"users"}
#                                    POST       /users(.:format)                                {:action=>"create", :controller=>"users"}
#                           new_user GET        /users/new(.:format)                            {:action=>"new", :controller=>"users"}
#                          edit_user GET        /users/:id/edit(.:format)                       {:action=>"edit", :controller=>"users"}
#                               user GET        /users/:id(.:format)                            {:action=>"show", :controller=>"users"}
#                                    PUT        /users/:id(.:format)                            {:action=>"update", :controller=>"users"}
#                                    DELETE     /users/:id(.:format)                            {:action=>"destroy", :controller=>"users"}
#                           speakers            /speakers(.:format)                             {:action=>"index", :controller=>"users"}
#                    admin_dashboard            /admin(.:format)                                {:action=>"index", :controller=>"admin/dashboard"}
#                     admin_contents GET        /admin/contents(.:format)                       {:action=>"index", :controller=>"admin/contents"}
#                                    POST       /admin/contents(.:format)                       {:action=>"create", :controller=>"admin/contents"}
#                  new_admin_content GET        /admin/contents/new(.:format)                   {:action=>"new", :controller=>"admin/contents"}
#                 edit_admin_content GET        /admin/contents/:id/edit(.:format)              {:action=>"edit", :controller=>"admin/contents"}
#                      admin_content GET        /admin/contents/:id(.:format)                   {:action=>"show", :controller=>"admin/contents"}
#                                    PUT        /admin/contents/:id(.:format)                   {:action=>"update", :controller=>"admin/contents"}
#                                    DELETE     /admin/contents/:id(.:format)                   {:action=>"destroy", :controller=>"admin/contents"}
#                     admin_features GET        /admin/features(.:format)                       {:action=>"index", :controller=>"admin/features"}
#                                    POST       /admin/features(.:format)                       {:action=>"create", :controller=>"admin/features"}
#                  new_admin_feature GET        /admin/features/new(.:format)                   {:action=>"new", :controller=>"admin/features"}
#                 edit_admin_feature GET        /admin/features/:id/edit(.:format)              {:action=>"edit", :controller=>"admin/features"}
#                      admin_feature GET        /admin/features/:id(.:format)                   {:action=>"show", :controller=>"admin/features"}
#                                    PUT        /admin/features/:id(.:format)                   {:action=>"update", :controller=>"admin/features"}
#                                    DELETE     /admin/features/:id(.:format)                   {:action=>"destroy", :controller=>"admin/features"}
#                        admin_posts GET        /admin/posts(.:format)                          {:action=>"index", :controller=>"admin/posts"}
#                                    POST       /admin/posts(.:format)                          {:action=>"create", :controller=>"admin/posts"}
#                     new_admin_post GET        /admin/posts/new(.:format)                      {:action=>"new", :controller=>"admin/posts"}
#                    edit_admin_post GET        /admin/posts/:id/edit(.:format)                 {:action=>"edit", :controller=>"admin/posts"}
#                         admin_post GET        /admin/posts/:id(.:format)                      {:action=>"show", :controller=>"admin/posts"}
#                                    PUT        /admin/posts/:id(.:format)                      {:action=>"update", :controller=>"admin/posts"}
#                                    DELETE     /admin/posts/:id(.:format)                      {:action=>"destroy", :controller=>"admin/posts"}
#                        admin_rooms GET        /admin/rooms(.:format)                          {:action=>"index", :controller=>"admin/rooms"}
#                                    POST       /admin/rooms(.:format)                          {:action=>"create", :controller=>"admin/rooms"}
#                     new_admin_room GET        /admin/rooms/new(.:format)                      {:action=>"new", :controller=>"admin/rooms"}
#                    edit_admin_room GET        /admin/rooms/:id/edit(.:format)                 {:action=>"edit", :controller=>"admin/rooms"}
#                         admin_room GET        /admin/rooms/:id(.:format)                      {:action=>"show", :controller=>"admin/rooms"}
#                                    PUT        /admin/rooms/:id(.:format)                      {:action=>"update", :controller=>"admin/rooms"}
#                                    DELETE     /admin/rooms/:id(.:format)                      {:action=>"destroy", :controller=>"admin/rooms"}
#                    admin_schedules GET        /admin/schedules(.:format)                      {:action=>"index", :controller=>"admin/schedules"}
#                                    POST       /admin/schedules(.:format)                      {:action=>"create", :controller=>"admin/schedules"}
#                 new_admin_schedule GET        /admin/schedules/new(.:format)                  {:action=>"new", :controller=>"admin/schedules"}
#                edit_admin_schedule GET        /admin/schedules/:id/edit(.:format)             {:action=>"edit", :controller=>"admin/schedules"}

app/models/sesja.rb
class Sesja < ActiveRecord::Base
  belongs_to :user, :autosave => true
  has_one :schedule

  default_scope where("sesjas.version_tag = ?", VERSION_TAG).order('sesjas.permalink ASC')

  scope :by_creation, :order => 'sesjas.created_at DESC'

  scope :pending_confirmation, lambda { where( "sesjas.accepted_at is null" ) }
  scope :displayable,          lambda { includes(:user).where( "sesjas.rsvped_at is not null" ) }
  scope :randomized,           lambda { order "random()" }

  validates :user, :presence => true
  validates :title, :presence => true, :length => {:within => 0..64}
  validates :abstract, :presence => true, :length => {:within => 0..1024}
  validates_inclusion_of :level, :in => 0..3

  before_save :set_permalink, :seoize_permalink

  has_many :comments, :as => :commentable

  def accepted?
    !!self.accepted_at
  end

  def rsvped?
    !!self.rsvped_at
  end

  def mailed?
    !!self.mailed_at
  end

  def to_s
    permalink
  end

  protected

  def seoize_permalink
    Formatter.seoize!(self.permalink)
  end

  def set_permalink
    # assigning the string actually is a ref
    # so dup is necesary. :P
    self.permalink = self.title.dup
  end
end






# == Schema Information
#
# Table name: sesjas
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  abstract    :text
#  level       :integer
#  keywords    :string(255)
#  user_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  accepted_at :datetime
#  mailed_at   :datetime
#  rsvped_at   :datetime
#  permalink   :string(255)
#  version_tag :string(255)
#

app/controllers/sesjas_controller.rb
class SesjasController < ApplicationController
  load_and_authorize_resource
  caches_page [:index]

  def index
    response.headers['Cache-Control'] = "public, max-age=#{CACHE_CONTROL__MAX_AGE}"
    respond_to do |format|
      format.html 
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def new
    respond_to do |format|
      format.html
    end
  end

  def edit
  end

  def create
    respond_to do |format|
      if @sesja.save
        expire_page :action => :index
        format.html { redirect_to(@sesja, :notice => 'Session was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @sesja.update_attributes(params[:sesja])
        expire_page :action => :index
        format.html { redirect_to(@sesja, :notice => 'Session was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @sesja.destroy
    expire_page :action => :index
    respond_to do |format|
      format.html { redirect_to(sesjas_url) }
    end
  end
end

app/views/sesjas/_form.html.haml
= semantic_form_for @sesja, :html => {:multipart => true} do |f|
  = f.inputs do
    = f.input :title, :required => true, :placeholder => "the working title for your presentation"
    = f.input :abstract, :required => true, :placeholder => "a brief synopsis of the presentation and topic", :as => :text, :input_html => { :class => 'autogrow', :rows => 8, :maxlength => 1000  }
    = f.input :level, :required => true, :as => :select, :collection => [["introductory", 1], ["intermediate", 2], ["advanced", 3]], :prompt => "select the level your session is targeted to"
    = f.input :keywords, :required => true, :placeholder => "relevant, words, for, your, session"
    = f.input :permalink
    - if current_user.admin?
      = f.input :accepted_at
      = f.input :mailed_at
      = f.input :rsvped_at
  = f.buttons do
    = f.commit_button :label => "Submit Session"

-# = form_for @sesja, :html => {:multipart => true} do |f|
-#   - if @sesja.errors.any?
-#     - errors = @sesja.errors
-#     - errors.merge!(@sesja.user.errors) unless @sesja.user.blank?
-#     #error_explanation
-#       %h4
-#         = pluralize(errors.count, "error")
-#         prohibited this
-#         sesja from being saved:
-#       %ul
-#         - errors.full_messages.each do |msg|
-#           %li= msg
-#   %fieldset
-#     %legend edit your session
-#     %ul
-#       %li
-#         = f.label :title, :class => "required"
-#         = f.text_field :title, :placeholder => "the working title for your presentation"
-#         .hint the working title for your presentation
-#       %li
-#         = f.label :abstract, "description", :class => "required"
-#         = f.text_area :abstract, :placeholder => "a brief synopsis of the presentation and topic"
-#         .hint describe your proposal in 1k characters or less
-#       %li
-#         = f.label :level, :class => "required"
-#         = f.select :level, [["introductory", 1], ["intermediate", 2], ["advanced", 3]], :prompt => "select the level your session is targeted to"
-#         .hint select the level your session is targeted to
-#       %li
-#         = f.label :keywords
-#         = f.text_field :keywords, :placeholder => "relevant, words, for, your, session"
-#         .hint comma-separated list of keywords to help describe your session
-#   %fieldset
-#     %ul
-#       %li
-#         %button#sesja_submit{:name => "commit", :type => "submit"} submit

app/views/sesjas/_sesja.html.haml
.show
  %h3= link_to "#{sesja.title.downcase}", sesja
  %ul
    %li.context.speaker
      %span speaker:
      = link_to sesja.user.full_name, user_path(sesja.user)
    %li.description.long-text
      = allow_markup(sesja.abstract)

    - if sesja.level.present?
      %li.details.level
        %span level:
        =  %w(introductory intermediate advanced)[sesja.level-1]
    - if sesja.keywords.try(:strip).present?
      %li.details.keywords
        %span keywords:
        = sesja.keywords

  - if user_signed_in? && current_user.admin?
    .actions
      %ul
        %li= link_to 'Show', sesja
        %li= link_to 'Edit', edit_sesja_path(sesja)
        %li= link_to 'Destroy', sesja, :confirm => 'Are you sure you wish to delete this sesja?', :method => :delete

app/views/sesjas/edit.html.haml
- if user_signed_in? && current_user.speaker?
  %fieldset.actions
    %legend= "Manage #{@sesja.title}"
    %ul
      - if can?(:show, Sesja)
        %li= link_to "view", sesja_path(@sesja)

%h4.section-title session description
= render 'form'

app/views/sesjas/index.html.haml
%h4.section-title session lineup 
- if user_signed_in? && current_user.admin?
  %p= pluralize @sesjas.displayable.count, 'session'
  %p= pluralize @sesjas.displayable.select('distinct user_id').count, 'speaker'
.lineup
  = render :partial => "sesja", :collection => @sesjas.displayable

- if user_signed_in? && current_user.admin?
  = render :partial => "shared/actions", :locals => {:model => Sesja.new, :current_action => :index}

- content_for :javascript do
  :javascript
    SEARCH_PLACEHOLDER_TEXT = "type to filter by title";
  = javascript_include_tag "index"

app/views/sesjas/new.html.haml
= render 'form'
= render :partial => "shared/actions", :locals => {:model => @sesja, :current_action => :create}

app/views/sesjas/show.html.haml
- if user_signed_in? && current_user.speaker?
  %fieldset.actions
    %legend= "Manage #{@sesja.title}"
    %ul
      - if can?(:update, Sesja)
        %li= link_to "Edit", edit_sesja_path(@sesja)

%h4.section-title session description
= render :partial => "sesjas/sesja", :locals => {:sesja => @sesja}

- if Feature.ok? :comments
  #comments
    %ul.comments-list
      - @sesja.comments.each do |comment|
        %li
          /
            = comment.id
          %span.email= comment.email.split('@').first
          = comment.comment

    - semantic_form_for [@sesja, @comment || @sesja.comments.build] do |f|
      = f.semantic_errors
      = f.inputs do
        = f.input :comment, :rows => 3
        = f.input :email
      = f.buttons